services:
  database:
    container_name: communications-development-database
    image: postgres:16.2
    restart: always
    shm_size: 256mb
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME} -h database
      interval: 2s
      timeout: 3s
      retries: 120
    ports:
      - ${DB_PORT}:5432
    networks:
      - database-network

  redis:
    container_name: commmunications-development-redis
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - redis-network

networks:
  database-network:
  redis-network:
