# Generated by Django 5.0.3 on 2024-04-21 21:11

import core.models.functions.concat_string
import core.models.mixins.created_mixin
import core.models.mixins.updated_mixin
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                ("foundation_date", models.DateField(verbose_name="foundation date")),
            ],
            options={
                "verbose_name": "mobile operator",
                "verbose_name_plural": "mobile operators",
                "db_table": '"mobile_communications"."operator"',
                "ordering": ["title", "foundation_date"],
            },
            bases=(
                core.models.mixins.created_mixin.CreatedMixin,
                core.models.mixins.updated_mixin.UpdatedMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="OperatorSubscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.operator",
                        verbose_name="operator",
                    ),
                ),
            ],
            options={
                "verbose_name": "relation of operator and subscriber",
                "verbose_name_plural": "relations of operator and subscriber",
                "db_table": '"mobile_communications"."operator_subscriber"',
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=64, verbose_name="first name")),
                ("last_name", models.CharField(max_length=64, verbose_name="last name")),
                (
                    "full_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=core.models.functions.concat_string.ConcatString(
                            "first_name", models.Value(" "), "last_name"
                        ),
                        output_field=models.CharField(max_length=129),
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="birth day")),
                (
                    "passport",
                    models.CharField(
                        help_text='Passport number has a format like "0000-000000"',
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}-\\d{6}$",
                                'incorrect passport number format (example: "0000-000000")',
                            )
                        ],
                        verbose_name="passport number",
                    ),
                ),
                (
                    "operators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        through="core.OperatorSubscriber",
                        to="core.operator",
                        verbose_name="operators",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscriber",
                "verbose_name_plural": "subscribers",
                "db_table": '"mobile_communications"."subscriber"',
                "ordering": ["first_name", "last_name", "birth_date"],
            },
            bases=(
                core.models.mixins.created_mixin.CreatedMixin,
                core.models.mixins.updated_mixin.UpdatedMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="operatorsubscriber",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.subscriber",
                verbose_name="subscriber",
            ),
        ),
        migrations.AddField(
            model_name="operator",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                through="core.OperatorSubscriber",
                to="core.subscriber",
                verbose_name="subscribers",
            ),
        ),
        migrations.CreateModel(
            name="SubscriberCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="start time")),
                ("duration", models.DurationField(verbose_name="duration")),
                (
                    "caller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="made_calls",
                        to="core.subscriber",
                        verbose_name="caller",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_calls",
                        to="core.subscriber",
                        verbose_name="call receiver",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscriber call",
                "verbose_name_plural": "subscribers calls",
                "db_table": '"mobile_communications"."subscriber_call"',
                "ordering": ["start", "caller__full_name", "receiver__full_name"],
            },
            bases=(
                core.models.mixins.created_mixin.CreatedMixin,
                core.models.mixins.updated_mixin.UpdatedMixin,
                models.Model,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="operatorsubscriber",
            unique_together={("operator", "subscriber")},
        ),
        migrations.AddConstraint(
            model_name="subscribercall",
            constraint=models.CheckConstraint(
                check=models.Q(("caller_id", models.F("receiver_id")), _negated=True),
                name="check_not_equal_caller_and_receiver",
            ),
        ),
    ]
