# Generated by Django 5.0.4 on 2024-04-18 20:51

import calls.models.functions.concat_string
import calls.models.mixins.created_mixin
import calls.models.mixins.updated_mixin
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                (
                    "full_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=calls.models.functions.concat_string.ConcatString(
                            "first_name", " ", "last_name"
                        ),
                        output_field=models.TextField(),
                    ),
                ),
                ("birth_date", models.DateField()),
                (
                    "passport_number",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", "Incorrect passport number format"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["first_name", "last_name", "birth_date"],
            },
            bases=(
                calls.models.mixins.created_mixin.CreatedMixin,
                calls.models.mixins.updated_mixin.UpdatedMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("foundation_date", models.DateField()),
                (
                    "subscribers",
                    models.ManyToManyField(related_name="operators", to="calls.subscriber"),
                ),
            ],
            options={
                "ordering": ["title", "foundation_date"],
            },
            bases=(
                calls.models.mixins.created_mixin.CreatedMixin,
                calls.models.mixins.updated_mixin.UpdatedMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SubscriberCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("start", models.DateTimeField()),
                ("duration", models.PositiveIntegerField()),
                (
                    "caller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="made_calls",
                        to="calls.subscriber",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_calls",
                        to="calls.subscriber",
                    ),
                ),
            ],
            options={
                "ordering": ["caller__full_name", "receiver__full_name"],
            },
            bases=(
                calls.models.mixins.created_mixin.CreatedMixin,
                calls.models.mixins.updated_mixin.UpdatedMixin,
                models.Model,
            ),
        ),
    ]
