# Generated by Django 5.0.3 on 2024-04-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={
                "ordering": ("user__full_name", "birth_date"),
                "verbose_name": "subscriber",
                "verbose_name_plural": "subscribers",
            },
        ),
        migrations.AlterModelOptions(
            name="subscribercall",
            options={
                "ordering": ("caller__user__full_name", "receiver__user__full_name"),
                "verbose_name": "subscriber call",
                "verbose_name_plural": "subscribers calls",
            },
        ),
    ]
