services:
  database:
    container_name: communications-production-database
    image: postgres:16.2
    restart: always
    shm_size: 256mb
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: pg_isready -d ${DB_NAME} -h database -U ${DB_USER}
      interval: 2s
      timeout: 3s
      retries: 120
    networks:
      - net

  server:
    container_name: communications-production-server
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        - DB_HOST=database
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - net

networks:
  net:
