services:
  database:
    container_name: communications-production-database
    image: postgres:16.2
    restart: always
    shm_size: 256mb
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME} -h database
      interval: 2s
      timeout: 3s
      retries: 120
    networks:
      - database-network

  redis:
    container_name: communications-production-redis
    image: redis
    networks:
      - redis-network

  server:
    container_name: communications-production-server
    build:
      context: ./
      dockerfile: ./docker/production/Dockerfile
      args:
        - DB_HOST=database
        - REDIS_HOST=redis
        - SERVER_PORT=${SERVER_PORT}
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - database-network
      - redis-network

networks:
  database-network:
  redis-network:
