# Generated by Django 5.0.6 on 2024-05-29 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="operators",
                through="calls.OperatorSubscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="subscribers",
            ),
        ),
    ]
