# Generated by Django 5.0.3 on 2024-04-24 12:01

import calls.models.validators.time_range_validator
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0002_alter_subscriber_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="birth_date",
            field=models.DateField(
                validators=[
                    calls.models.validators.time_range_validator.TimeRangeValidator(
                        start=datetime.date(1920, 1, 1)
                    )
                ],
                verbose_name="birth day",
            ),
        ),
        migrations.AlterField(
            model_name="subscribercall",
            name="start",
            field=models.DateTimeField(
                validators=[calls.models.validators.time_range_validator.TimeRangeValidator()],
                verbose_name="start time",
            ),
        ),
    ]
