# Generated by Django 5.0.3 on 2024-04-25 17:18

import calls.models.validators.duration_positivity_validator
import calls.models.validators.time_range_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_alter_subscriber_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operator",
            options={
                "ordering": ("title", "foundation_date"),
                "verbose_name": "operator",
                "verbose_name_plural": "operators",
            },
        ),
        migrations.AlterField(
            model_name="operator",
            name="foundation_date",
            field=models.DateField(
                validators=[calls.models.validators.time_range_validator.TimeRangeValidator()],
                verbose_name="foundation date",
            ),
        ),
        migrations.AlterField(
            model_name="subscribercall",
            name="duration",
            field=models.DurationField(
                validators=[calls.models.validators.duration_positivity_validator],
                verbose_name="duration",
            ),
        ),
    ]
