# Generated by Django 5.0.6 on 2024-05-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0005_alter_operator_subscribers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={
                "ordering": ("user__first_name", "user__last_name", "birth_date"),
                "verbose_name": "subscriber",
                "verbose_name_plural": "subscribers",
            },
        ),
        migrations.AlterModelOptions(
            name="subscribercall",
            options={
                "ordering": (
                    "caller__user__first_name",
                    "caller__user__last_name",
                    "receiver__user__first_name",
                    "receiver__user__last_name",
                ),
                "verbose_name": "subscriber call",
                "verbose_name_plural": "subscribers calls",
            },
        ),
    ]
